Priyal Gupta
PRN: 25070123087
Experiment 14: Data binning and Data Formatting using Python

In [ ]:
import pandas as pd
import numpy as np

data ={
'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
'Price':[55000,20000,30000,2000,8000,45000],
'Units_sold':[25,60,35,80,50,15]
}
df = pd.DataFrame(data)
print(df)

      Product  Price  Units_sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
# Data Binning
bins1 = [0,10000,30000,60000]
labels1 = ['Low','Medium','High']
df['Price_Category'] = pd.cut(df['Price'],bins=bins1,labels=labels1)

print(df)

      Product  Price  Units_sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [ ]:
# Binning Units sold
bins2 =[0,30,60,100]
labels2 =['Low Sales','Medium Sales','High Sales']

df['Sales_Category'] = pd.cut(df['Units_sold'],bins=bins2,labels=labels2)
print(df)

      Product  Price  Units_sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low Sales
1      Mobile  20000          60         Medium   Medium Sales
2      Tablet  30000          35         Medium   Medium Sales
3  Headphones   2000          80            Low     High Sales
4  Smartwatch   8000          50            Low   Medium Sales
5      Camera  45000          15           High      Low Sales

In [ ]:
# Data Formatting
# Convert Data Type

print(df.dtypes)

df['Units_sold']= df['Units_sold'].astype(float)
print(df.dtypes)
df

Product             object
Price                int64
Units_sold         float64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_sold         float64
Price_Category    category
Sales_Category    category
dtype: object

      Product  Price  Units_sold Price_Category Sales_Category
0      Laptop  55000        25.0           High      Low Sales
1      Mobile  20000        60.0         Medium   Medium Sales
2      Tablet  30000        35.0         Medium   Medium Sales
3  Headphones   2000        80.0            Low     High Sales
4  Smartwatch   8000        50.0            Low   Medium Sales
5      Camera  45000        15.0           High      Low Sales

In [ ]:
# Convert text to uppercase for the 'Product' column
df['Product'].str.upper()

print(df)

      Product  Price  Units_sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [ ]:
# Rounding Values
df['Price'] = df['Price'].round(2)
print(df)

      Product  Price  Units_sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [ ]:
# Additional
# Sort Data & overwriting it.
df.sort_values(by='Price', ascending=False, inplace=True)
df

      Product  Price  Units_sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
5      CAMERA  45000        15.0           High      Low Sales
2      TABLET  30000        35.0         Medium   Medium Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales

In [ ]:
# Display Unique Values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [ ]:
# Dataset: Food Delivery orders
import pandas as pd
import numpy as np

data ={
'Order_ID': ['01','02','03','04','05','06','07','08'],
'Order_Value':[250,450,120,600,300,150,500,220], # Added np.nan to make it 8 elements
'Delivery_Time':[30,45,25,60,35,20,50,28], # Formatted as a list of 8 strings
'Distance_km':[5,8,3,10,6,2,9,4]
}
df = pd.DataFrame(data)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [ ]:
# Binning Order Value
bins =[0,200,400,700]
labels ={'Low Order','Medium Order','High Order'}
df['Order_Category'] = pd.cut(df['Order_Value'],bins=bins,labels=labels)

print(df)

  Order_ID  Order_Value  Delivery_Date  Distance_km Order_Category
0       01          250             30            5   Medium Order
1       02          450             45            8     High Order
2       03          120             25            3      Low Order
3       04          600             60           10     High Order
4       05          300             35            6   Medium Order
5       06          150             20            2      Low Order
6       07          500             50            9     High Order
7       08          220             28            4   Medium Order

In [ ]:
# Binning delivery time
bins2 = [0,30,45,70]
labels2 = ['Fast','Normal','Slow']

df['Delivery_Speed'] = pd.cut(df['Delivery_Time'], bins=bins2, labels=labels2)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Delivery_Speed
0       01          250             30            5           Fast
1       02          450             45            8         Normal
2       03          120             25            3           Fast
3       04          600             60           10           Slow
4       05          300             35            6         Normal
5       06          150             20            2           Fast
6       07          500             50            9           Slow
7       08          220             28            4           Fast

In [ ]:
# Binning distance_km
bins3 = [0,5,8,10]
lables3 = ['Short','Medium','Long']
df['Delivery_Distance'] = pd.cut(df['Distance_km'], bins=bins3, labels=lables3)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Delivery_Speed  \
0       01          250             30            5           Fast
1       02          450             45            8         Normal
2       03          120             25            3           Fast
3       04          600             60           10           Slow
4       05          300             35            6         Normal
5       06          150             20            2           Fast
6       07          500             50            9           Slow
7       08          220             28            4           Fast

  Delivery_Distance
0             Short
1            Medium
2             Short
3              Long
4            Medium
5             Short
6              Long
7             Short

In [ ]:
# Count of categories
print(df['Order_Category'].value_counts())
print(df)

Order_Category
Medium Order    3
High Order      3
Low Order       2
Name: count, dtype: int64
  Order_ID  Order_Value  Delivery_Time  Distance_km Delivery_Speed  \
0       01          250             30            5           Fast
1       02          450             45            8         Normal
2       03          120             25            3           Fast
3       04          600             60           10           Slow
4       05          300             35            6         Normal
5       06          150             20            2           Fast
6       07          500             50            9           Slow
7       08          220             28            4           Fast

  Delivery_Distance Order_Category
0             Short   Medium Order
1            Medium     High Order
2             Short      Low Order
3              Long     High Order
4            Medium   Medium Order
5             Short      Low Order
6              Long     High Order
7             Short   Medium Order

In [ ]:
# Sorting
print(df.sort_values(by=['Order_Value']))

  Order_ID  Order_Value  Delivery_Time  Distance_km Delivery_Speed  \
2       03          120             25            3           Fast
5       06          150             20            2           Fast
7       08          220             28            4           Fast
0       01          250             30            5           Fast
4       05          300             35            6         Normal
1       02          450             45            8         Normal
6       07          500             50            9           Slow
3       04          600             60           10           Slow

  Delivery_Distance Order_Category
2             Short      Low Order
5             Short      Low Order
7             Short   Medium Order
0             Short   Medium Order
4            Medium   Medium Order
1            Medium     High Order
6              Long     High Order
3              Long     High Order

In [ ]:
# Converting dataset into uppercase
df['Order_Value'] = df['Order_Value'].astype(str).str.upper()
print(df)

  Order_ID Order_Value  Delivery_Time  Distance_km Delivery_Speed  \
0       01         250             30            5           Fast
1       02         450             45            8         Normal
2       03         120             25            3           Fast
3       04         600             60           10           Slow
4       05         300             35            6         Normal
5       06         150             20            2           Fast
6       07         500             50            9           Slow
7       08         220             28            4           Fast

  Delivery_Distance Order_Category
0             Short   Medium Order
1            Medium     High Order
2             Short      Low Order
3              Long     High Order
4            Medium   Medium Order
5             Short      Low Order
6              Long     High Order
7             Short   Medium Order

In [ ]:
# Formatting the dataset

In [ ]:
# Data Formatting
# Convert Data Type

df['Order_Value']= df['Order_Value'].astype(float)
print(df.dtypes)
df

Order_ID               object
Order_Value           float64
Delivery_Time           int64
Distance_km             int64
Delivery_Speed       category
Delivery_Distance    category
Order_Category       category
dtype: object

,Order_ID,Order_Value,Delivery_Time,Distance_km,Delivery_Speed,Delivery_Distance,Order_Category
0,01,250.0,30,5,Fast,Short,Medium Order
1,02,450.0,45,8,Normal,Medium,High Order
2,03,120.0,25,3,Fast,Short,Low Order
3,04,600.0,60,10,Slow,Long,High Order
4,05,300.0,35,6,Normal,Medium,Medium Order
5,06,150.0,20,2,Fast,Short,Low Order
6,07,500.0,50,9,Slow,Long,High Order
7,08,220.0,28,4,Fast,Short,Medium Order